# Generated by Django 5.2.9 on 2025-12-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('land_preparation', 'Land Preparation'), ('planting', 'Planting'), ('weeding', 'Weeding'), ('fertilizer_application', 'Fertilizer Application'), ('pesticide_application', 'Pesticide Application'), ('irrigation', 'Irrigation'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post-Harvest Activity')], max_length=30)),
                ('crop_name', models.CharField(blank=True, max_length=100)),
                ('field_section', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('quantity_used', models.CharField(blank=True, help_text='e.g., 50kg fertilizer, 2L pesticide', max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in KES', max_digits=10, null=True)),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('workers_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_activities', to='farms.farmprofile')),
            ],
            options={
                'verbose_name_plural': 'Field Activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('general', 'General Note'), ('planting', 'Planting Activity'), ('harvesting', 'Harvesting'), ('spraying', 'Spraying/Pesticide'), ('fertilizing', 'Fertilizing'), ('irrigation', 'Irrigation'), ('observation', 'Field Observation'), ('weather', 'Weather Note'), ('other', 'Other')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Detailed notes')),
                ('crop_name', models.CharField(blank=True, help_text='Which crop (if applicable)', max_length=100)),
                ('field_section', models.CharField(blank=True, help_text='Field name/section', max_length=100)),
                ('photo_url', models.URLField(blank=True, help_text='Photo URL', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='farms.farmprofile')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['farm_profile', 'entry_date'], name='journal_jou_farm_pr_af0cb1_idx'), models.Index(fields=['entry_type'], name='journal_jou_entry_t_d2ef18_idx')],
            },
        ),
    ]
