# Generated by Django 5.2.9 on 2025-12-04 08:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Maize', 'Maize'), ('Beans', 'Beans'), ('Potatoes', 'Potatoes'), ('Tomatoes', 'Tomatoes'), ('Cabbage', 'Cabbage'), ('Kale', 'Kale'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Sugarcane', 'Sugarcane'), ('Bananas', 'Bananas'), ('Onions', 'Onions'), ('Carrots', 'Carrots'), ('Other', 'Other')], max_length=50)),
                ('market', models.CharField(choices=[('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('meru', 'Meru'), ('national', 'National Average')], default='national', max_length=50)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('kace', 'KACE - Kenya Agricultural Commodity Exchange'), ('manual', 'Manual Entry'), ('api', 'External API'), ('scraper', 'Web Scraper')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_prices',
                'ordering': ['-date', 'crop'],
                'indexes': [models.Index(fields=['crop', '-date'], name='market_pric_crop_fac6e2_idx'), models.Index(fields=['market', '-date'], name='market_pric_market_63862e_idx'), models.Index(fields=['crop', 'market', '-date'], name='market_pric_crop_fd7bcc_idx')],
                'unique_together': {('crop', 'market', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Maize', 'Maize'), ('Beans', 'Beans'), ('Potatoes', 'Potatoes'), ('Tomatoes', 'Tomatoes'), ('Cabbage', 'Cabbage'), ('Kale', 'Kale'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Sugarcane', 'Sugarcane'), ('Bananas', 'Bananas'), ('Onions', 'Onions'), ('Carrots', 'Carrots'), ('Other', 'Other')], max_length=50)),
                ('market', models.CharField(choices=[('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('meru', 'Meru'), ('national', 'National Average')], default='national', max_length=50)),
                ('forecast_date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence level of prediction (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MinValueValidator(Decimal('100'))])),
                ('model_used', models.CharField(choices=[('linear', 'Linear Regression'), ('arima', 'ARIMA Time Series'), ('prophet', 'Facebook Prophet'), ('gemini', 'Google Gemini AI'), ('average', 'Moving Average')], default='average', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'price_forecasts',
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['crop', 'forecast_date'], name='price_forec_crop_d229cb_idx'), models.Index(fields=['crop', 'market', 'forecast_date'], name='price_forec_crop_695bc5_idx')],
                'unique_together': {('crop', 'market', 'forecast_date', 'model_used')},
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Maize', 'Maize'), ('Beans', 'Beans'), ('Potatoes', 'Potatoes'), ('Tomatoes', 'Tomatoes'), ('Cabbage', 'Cabbage'), ('Kale', 'Kale'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Sugarcane', 'Sugarcane'), ('Bananas', 'Bananas'), ('Onions', 'Onions'), ('Carrots', 'Carrots'), ('Other', 'Other')], max_length=50)),
                ('target_price', models.DecimalField(decimal_places=2, help_text='Alert when price reaches or exceeds this amount (KES/kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market', models.CharField(choices=[('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('meru', 'Meru'), ('national', 'National Average')], default='national', help_text='Which market to monitor', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price when alert was triggered', max_digits=10, null=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='price_alert_user_id_600b95_idx'), models.Index(fields=['crop', 'is_active'], name='price_alert_crop_0c4e16_idx')],
            },
        ),
    ]
