# Generated by Django 5.2.9 on 2025-12-04 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('planting_season', models.CharField(help_text='Best time to plant', max_length=200)),
                ('time_to_harvest_days', models.IntegerField(help_text='Average days to maturity')),
                ('seed_rate_per_acre', models.CharField(help_text='e.g., 25kg per acre', max_length=100)),
                ('spacing', models.CharField(help_text='e.g., 30cm x 15cm', max_length=100)),
                ('soil_ph_min', models.DecimalField(decimal_places=1, default=5.5, max_digits=3)),
                ('soil_ph_max', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('water_requirement', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=50)),
                ('fertilizer_recommendation', models.TextField(help_text='General fertilizer advice')),
                ('common_challenges', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text="User's question or image description")),
                ('response', models.TextField(help_text='AI generated advice')),
                ('context', models.CharField(default='general', help_text='e.g., pest_id, crop_advice', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='User rating 1-5', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agronomy_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('pest', 'Pest'), ('disease', 'Disease'), ('weed', 'Weed')], max_length=20)),
                ('symptoms', models.TextField()),
                ('prevention', models.TextField(blank=True)),
                ('treatment_organic', models.TextField(blank=True, help_text='Organic control methods')),
                ('treatment_chemical', models.TextField(blank=True, help_text='Chemical control methods')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pests_diseases', to='agronomy.cropguide')),
            ],
        ),
    ]
