# Generated by Django 5.2.9 on 2025-12-04 09:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policy_type', models.CharField(choices=[('drought', 'Drought Insurance'), ('flood', 'Flood Insurance'), ('multi_peril', 'Multi-Peril (Drought + Flood)'), ('excess_rain', 'Excess Rainfall Insurance'), ('temperature', 'Extreme Temperature Insurance')], max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, help_text='Maximum payout amount (KES)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))])),
                ('premium_amount', models.DecimalField(decimal_places=2, help_text='Premium to be paid (KES)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100'))])),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='quarterly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('claimed', 'Claimed')], default='draft', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='farms.farmprofile')),
            ],
            options={
                'db_table': 'insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_policy_type', models.CharField(choices=[('drought', 'Drought Insurance'), ('flood', 'Flood Insurance'), ('multi_peril', 'Multi-Peril (Drought + Flood)'), ('excess_rain', 'Excess Rainfall Insurance'), ('temperature', 'Extreme Temperature Insurance')], max_length=20)),
                ('recommended_coverage', models.DecimalField(decimal_places=2, help_text='Recommended coverage amount (KES)', max_digits=12)),
                ('recommended_premium', models.DecimalField(decimal_places=2, help_text='Estimated premium (KES)', max_digits=10)),
                ('risk_assessment_summary', models.TextField(help_text='Why this policy is recommended')),
                ('confidence_score', models.IntegerField(default=50, help_text='Confidence in recommendation (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_recommendations', to='farms.farmprofile')),
            ],
            options={
                'db_table': 'policy_recommendations',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('rainfall_deficit', 'Rainfall Below Threshold'), ('rainfall_excess', 'Rainfall Above Threshold'), ('temperature_high', 'Temperature Above Threshold'), ('temperature_low', 'Temperature Below Threshold'), ('consecutive_dry_days', 'Consecutive Dry Days')], max_length=30)),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Threshold value for trigger', max_digits=10)),
                ('measurement_period_days', models.IntegerField(default=30, help_text='Period over which to measure (e.g., 30 days)')),
                ('payout_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of coverage to payout (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_triggered', models.BooleanField(default=False)),
                ('trigger_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='insurance.insurancepolicy')),
            ],
            options={
                'db_table': 'policy_triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('automatic', 'Automatic (Trigger-based)'), ('manual', 'Manual Submission')], max_length=20)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True, help_text='Claim description/reason')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('filed_date', models.DateField(auto_now_add=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='insurance.policytrigger')),
            ],
            options={
                'db_table': 'insurance_claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.insurancepolicy')),
            ],
            options={
                'db_table': 'premium_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['farm_profile', 'status'], name='insurance_p_farm_pr_b7abf6_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='insurance_p_policy__67856c_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['policy', 'status'], name='insurance_c_policy__a6ac3f_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['claim_number'], name='insurance_c_claim_n_6e8b18_idx'),
        ),
    ]
