# Generated by Django 5.2.9 on 2025-12-04 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('forecast_date', models.DateField(blank=True, help_text='For forecasts: the date being forecasted. Null for historical data.', null=True)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0, help_text='Rainfall in millimeters', max_digits=7)),
                ('humidity', models.IntegerField(blank=True, help_text='Relative humidity percentage', null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('stormy', 'Stormy'), ('partly_cloudy', 'Partly Cloudy')], default='clear', max_length=20)),
                ('source', models.CharField(choices=[('openweather', 'OpenWeatherMap'), ('manual', 'Manual Entry'), ('sensor', 'Weather Station')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'latitude', 'longitude'], name='weather_dat_date_b62120_idx'), models.Index(fields=['forecast_date'], name='weather_dat_forecas_cfda81_idx')],
                'unique_together': {('latitude', 'longitude', 'date', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='ClimateRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('drought_risk', models.IntegerField(default=0, help_text='Drought risk score (0-100)')),
                ('flood_risk', models.IntegerField(default=0, help_text='Flood risk score (0-100)')),
                ('extreme_temp_risk', models.IntegerField(default=0, help_text='Extreme temperature risk score (0-100)')),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('recommendations', models.TextField(blank=True, help_text='Risk mitigation recommendations')),
                ('confidence', models.IntegerField(default=50, help_text='Confidence level of assessment (0-100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_risks', to='farms.farmprofile')),
            ],
            options={
                'db_table': 'climate_risks',
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['farm_profile', '-assessment_date'], name='climate_ris_farm_pr_6ac248_idx'), models.Index(fields=['overall_risk_level'], name='climate_ris_overall_c5f23a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NDVIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_value', models.DecimalField(decimal_places=3, help_text='NDVI value: -1 to 1 (0.3-0.8 = healthy crops)', max_digits=4)),
                ('image_date', models.DateField(db_index=True)),
                ('health_status', models.CharField(choices=[('poor', 'Poor - NDVI < 0.2'), ('fair', 'Fair - NDVI 0.2-0.4'), ('good', 'Good - NDVI 0.4-0.6'), ('excellent', 'Excellent - NDVI > 0.6')], max_length=20)),
                ('source', models.CharField(choices=[('sentinel', 'Sentinel-2'), ('landsat', 'Landsat'), ('google_ee', 'Google Earth Engine'), ('manual', 'Manual Calculation')], default='manual', max_length=20)),
                ('cloud_cover_percent', models.IntegerField(blank=True, help_text='Cloud coverage percentage (lower is better)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_data', to='farms.farmprofile')),
            ],
            options={
                'db_table': 'ndvi_data',
                'ordering': ['-image_date'],
                'indexes': [models.Index(fields=['farm_profile', '-image_date'], name='ndvi_data_farm_pr_0eaf89_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drought', 'Drought Warning'), ('heavy_rain', 'Heavy Rainfall Warning'), ('storm', 'Storm Warning'), ('frost', 'Frost Warning'), ('heatwave', 'Heatwave Warning')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weather_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', '-created_at'], name='weather_ale_user_id_95961d_idx'), models.Index(fields=['alert_type', 'severity'], name='weather_ale_alert_t_7d780b_idx')],
            },
        ),
    ]
