# Generated by Django 5.2.9 on 2025-12-04 06:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('kiambu', 'Kiambu'), ('meru', 'Meru'), ('kisumu', 'Kisumu'), ('uasin_gishu', 'Uasin Gishu'), ('trans_nzoia', 'Trans Nzoia'), ('bungoma', 'Bungoma'), ('kakamega', 'Kakamega'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(help_text='Town/Village name', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('size_acres', models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('crops', models.JSONField(default=list, help_text='List of crops grown on this farm')),
                ('farming_type', models.CharField(choices=[('subsistence', 'Subsistence'), ('commercial', 'Commercial'), ('mixed', 'Mixed')], default='subsistence', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('pesticides', 'Pesticides'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('transport', 'Transport'), ('irrigation', 'Irrigation'), ('rent', 'Land Rent'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='farms.farmprofile')),
            ],
            options={
                'db_table': 'expense_records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['farm_profile', '-date'], name='expense_rec_farm_pr_e620b8_idx'), models.Index(fields=['category', '-date'], name='expense_rec_categor_6688e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Maize', 'Maize'), ('Beans', 'Beans'), ('Potatoes', 'Potatoes'), ('Tomatoes', 'Tomatoes'), ('Cabbage', 'Cabbage'), ('Kale', 'Kale'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Sugarcane', 'Sugarcane'), ('Bananas', 'Bananas'), ('Other', 'Other')], max_length=50)),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Harvest quantity in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('harvest_date', models.DateField()),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Market price at harvest time (KES)', max_digits=10, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated value (KES)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='farms.farmprofile')),
            ],
            options={
                'db_table': 'harvest_records',
                'ordering': ['-harvest_date', '-created_at'],
                'indexes': [models.Index(fields=['farm_profile', '-harvest_date'], name='harvest_rec_farm_pr_0d00cb_idx'), models.Index(fields=['crop', '-harvest_date'], name='harvest_rec_crop_a04e7c_idx')],
            },
        ),
    ]
